Parameters:
  InstanceTypeParameters:
    Description: Only deploy t2.micro instances.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
  
  ImageIdParameters:
    Description: Only use ubuntu AMIs.
    Type: String
    Default: ami-06397100adf427136
    AllowedValues:
      - ami-06397100adf427136
      # - ami-08692d171e3cf02d6
  
  KeynameParameters:
    Description: use Kazmi-Key for all instances except when other is required.
    Type: String
    Default: "Kazmi-Key"
    AllowedValues:
      - "Kazmi-Key"
      - "alam-keypair"

Resources:

  MyLaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      AssociatePublicIpAddress: true
      ImageId: !Ref ImageIdParameters
      InstanceType: !Ref InstanceTypeParameters
      LaunchConfigurationName: MyLaunchConf
      KeyName: !Ref KeynameParameters
      SecurityGroups:
        - Fn::ImportValue: StackVPC-MyPublicSecurityGroup
      UserData:
        Fn::Base64: !Sub 
        - |
          #!/bin/bash
          set -x
          sleep 2m
          apt-get update -y
          apt-get install -y mysql-server php php-mysql
          apt-get install -y apache2 
          apt-get install -y unzip
          systemctl start apache2
          systemctl enable apache2
          cd /var/www
          rm -rf html
          wget https://s3.amazonaws.com/alamkey/html.zip
          unzip html.zip
          sed -i -e 's/localhost/${AppPrivateIp}/g' /var/www/html/config.php
        - AppPrivateIp:
            !ImportValue StackInstance-PrivIp

  MyAppASG:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      LoadBalancerNames:
        - Fn::ImportValue: StackLB-MyLB
      MaxSize: '4'
      MinSize: '2'
      VPCZoneIdentifier:
        - Fn::ImportValue: StackVPC-PublicSubnet
        - Fn::ImportValue: StackVPC-PublicSubnet2
      # UpdatePolicy:
      #   AutoScalingRollingUpdate:
      #     MinInstancesInService: 1  
      Tags:
        - Value: test    
          Key: AhsanPublic-ext
          PropagateAtLaunch: "false"

  MyDBLaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      InstanceId: !ImportValue StackInstance-MyPrivateInstance

  MyDBASG:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      LaunchConfigurationName: !Ref MyDBLaunchConfiguration
      MaxSize: '1'
      MinSize: '1'
      VPCZoneIdentifier:
        - Fn::ImportValue: StackVPC-PrivateSubnet
      Tags:
        - Value: "test"   
          Key: "Private-ext"
          PropagateAtLaunch: "true"

